'use client';

import Link from 'next/link';
import { useTheme } from '@/lib/theme-context';
import { BRAND_LABELS, PRODUCT_LABELS } from '@/lib/tokens';
import { PageHeader } from '@/components/page-header';

export default function Home() {
  const { brand, product, themeKey, isPlaceholder } = useTheme();

  return (
    <>
      <PageHeader
        eyebrow="Overview"
        title="ComPsych Design System — Reference"
        description="The live visual source of truth for tokens and (soon) components. Every value you see on this site is read from a CSS custom property generated by the four-tier token pipeline."
      />

      <section
        className="mb-10 p-6 rounded"
        style={{
          backgroundColor:
            'var(--sys-color-roles-surface-surface-container-sys-surface-container, #f3f4f6)',
          border:
            '1px solid var(--sys-color-roles-outline-sys-outline-variant, #d7dbe0)',
        }}
      >
        <div className="flex flex-col gap-1 mb-3">
          <div className="text-xs uppercase tracking-wider opacity-70">
            Active theme
          </div>
          <div className="text-xl font-semibold">
            {BRAND_LABELS[brand]} · {PRODUCT_LABELS[product]}
          </div>
          <div className="text-sm font-mono opacity-70">data-theme=&quot;{themeKey}&quot;</div>
        </div>
        {isPlaceholder && (
          <p
            className="text-sm mt-3 p-3 rounded"
            style={{
              backgroundColor:
                'var(--sys-color-roles-custom-warning-sys-warning-container, #fdeed9)',
              color:
                'var(--sys-color-roles-custom-warning-sys-on-warning-container, #3a2304)',
            }}
          >
            This theme is a placeholder. Token values will populate once the
            Figma system is defined upstream.
          </p>
        )}
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold mb-3">The critical rule</h2>
        <p className="text-sm max-w-3xl">
          Only <code>sys.*</code> tokens are applied in UI. <code>core.*</code>,{' '}
          <code>product.*</code>, and <code>brand.*</code> are internal plumbing.
          A component that references any of them directly will not respond to
          theme changes and will break white-labeling. This reference app
          follows the rule to the letter — every style below comes from a{' '}
          <code>var(--sys-*)</code> custom property.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold mb-3">Four-tier architecture</h2>
        <pre
          className="p-4 rounded text-sm font-mono overflow-x-auto"
          style={{
            backgroundColor:
              'var(--sys-color-roles-surface-surface-container-sys-surface-container-high, #eceeef)',
            color:
              'var(--sys-color-roles-surface-surface-sys-on-surface, #1b1d22)',
          }}
        >
          {'Brand  →  Core  →  Product  →  System\n\n' +
            '  (raw)    (primitives)   (theming)   (semantic, in UI)'}
        </pre>
      </section>

      <section className="grid gap-4 md:grid-cols-2 mb-10">
        <LinkCard
          href="/foundations"
          title="Foundations"
          description="Color, typography, spacing, elevation, radius, border width, and iconography — rendered live."
        />
        <LinkCard
          href="/components"
          title="Components"
          description="Gallery coming in the next phase. Specs are authoritative; each component lands here once its spec is stable."
          muted
        />
      </section>
    </>
  );
}

function LinkCard({
  href,
  title,
  description,
  muted,
}: {
  href: string;
  title: string;
  description: string;
  muted?: boolean;
}) {
  return (
    <Link
      href={href}
      className="block p-5 rounded"
      style={{
        border:
          '1px solid var(--sys-color-roles-outline-sys-outline-variant, #d7dbe0)',
        backgroundColor:
          'var(--sys-color-roles-surface-surface-container-sys-surface-container-lowest, #ffffff)',
        opacity: muted ? 0.75 : 1,
      }}
    >
      <div className="text-base font-semibold mb-1">{title}</div>
      <div
        className="text-sm"
        style={{
          color:
            'var(--sys-color-roles-surface-surface-sys-on-surface-variant, #565f6c)',
        }}
      >
        {description}
      </div>
    </Link>
  );
}
