/**
 * Concatenates every per-bundle `tokens/dist/<brand>-<product>/tokens.css`
 * into a single `reference/styles/themes.css`, with each theme's `:root`
 * block rewritten to a `[data-theme="<brand>-<product>"]` selector.
 *
 * The reference app imports the concatenated file once in `app/layout.tsx`;
 * switching the `data-theme` attribute on `<body>` then cascades every
 * `--sys-*` variable in the page.
 *
 * This script is idempotent and runs from `predev` and as part of `prebuild`.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REFERENCE_ROOT = resolve(__dirname, '..');
const REPO_ROOT = resolve(REFERENCE_ROOT, '..');
const DIST_DIR = resolve(REPO_ROOT, 'tokens', 'dist');
const OUT_PATH = resolve(REFERENCE_ROOT, 'styles', 'themes.css');
// We copy compsych-gro's tokens.ts into the app's lib/ folder so the typed
// import sits INSIDE the Next.js project root. Importing the external
// tokens/dist path works at dev time but trips up the RSC client-manifest
// bundler during `next build` (the external module fails the manifest
// lookup on some pages). The copy is cheap, idempotent, and keeps the
// runtime reads consistent.
const GENERATED_TOKENS_PATH = resolve(REFERENCE_ROOT, 'lib', 'generated-tokens.ts');
const DEFAULT_BUNDLE = 'compsych-gro';

function buildThemes(): void {
  if (!existsSync(DIST_DIR)) {
    throw new Error(
      `tokens/dist not found at ${DIST_DIR}. Run \`npm run build:tokens\` at the repo root first.`,
    );
  }

  const bundles = readdirSync(DIST_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();

  if (bundles.length === 0) {
    throw new Error(`No bundles found under ${DIST_DIR}.`);
  }

  const header = [
    '/**',
    ' * AUTO-GENERATED by reference/scripts/build-themes.ts.',
    ' * Do not edit by hand. Runs automatically on `npm run dev` / `npm run build`.',
    ' *',
    ' * One block per (brand × product) bundle. Switch the active theme by',
    ' * setting `data-theme="<brand>-<product>"` on <body> (or any ancestor).',
    ' */',
    '',
  ].join('\n');

  const blocks: string[] = [];
  for (const bundle of bundles) {
    const cssPath = join(DIST_DIR, bundle, 'tokens.css');
    if (!existsSync(cssPath)) {
      console.warn(`[build-themes] skipping ${bundle}: no tokens.css`);
      continue;
    }
    const raw = readFileSync(cssPath, 'utf8');

    // Extract the body of the `:root { ... }` block. Style Dictionary's
    // `css/variables` format emits a single :root block per file.
    const match = raw.match(/:root\s*\{([\s\S]*?)\}/);
    if (!match) {
      console.warn(`[build-themes] skipping ${bundle}: no :root block found in tokens.css`);
      continue;
    }
    const varsBody = match[1].trim();
    blocks.push(`[data-theme="${bundle}"] {\n${varsBody}\n}`);
  }

  // Default theme: duplicate compsych-gro under :root so the page renders
  // sensibly before the client-side theme context has hydrated.
  const fallback =
    blocks.find((b) => b.startsWith('[data-theme="compsych-gro"]'))?.replace(
      /^\[data-theme="[^"]+"\]/,
      ':root',
    ) ?? '';

  const out = [header, fallback, '', ...blocks, ''].join('\n\n');

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, out, 'utf8');

  console.log(`[build-themes] wrote ${bundles.length} theme blocks to ${OUT_PATH}`);

  // Copy the default bundle's typed tokens.ts into lib/ so the Next.js
  // app imports it from an in-tree path.
  const srcTs = resolve(DIST_DIR, DEFAULT_BUNDLE, 'tokens.ts');
  if (!existsSync(srcTs)) {
    throw new Error(
      `Expected ${DEFAULT_BUNDLE}/tokens.ts at ${srcTs}. Run \`npm run build:tokens\` first.`,
    );
  }
  mkdirSync(dirname(GENERATED_TOKENS_PATH), { recursive: true });
  copyFileSync(srcTs, GENERATED_TOKENS_PATH);
  console.log(`[build-themes] copied ${DEFAULT_BUNDLE}/tokens.ts → ${GENERATED_TOKENS_PATH}`);
}

buildThemes();
