// Auto-generated by tokens/build.ts. Do not edit by hand.
// Run `npm run build:tokens` to regenerate.

export const sys = {
  "colorRoles": {
    "accent": {
      "primary": {
        "sysPrimary": "#3f94a4",
        "sysOnPrimary": "#ffffff",
        "sysOnPrimaryContainer": "#ffffff",
        "sysPrimaryContainer": "#2c535f",
        "sysOnPrimaryContainerVariant": "#bde1e6"
      },
      "secondary": {
        "sysSecondary": "#f3f4f6",
        "sysOnSecondary": "#1b1d22",
        "sysSecondaryContainer": "#ffffff",
        "sysOnSecondaryContainer": "#1b1d22"
      },
      "tertiary": {
        "sysTertiary": "#367a8a",
        "sysOnTertiary": "#ffffff",
        "sysTertiaryContainer": "#9fdbb3",
        "sysOnTertiaryContainer": "#030c09"
      }
    },
    "custom": {
      "success": {
        "sysSuccess": "#278647",
        "sysOnSuccess": "#ffffff",
        "sysSuccessContainer": "#c4e9d0",
        "sysOnSuccessContainer": "#030c09"
      },
      "warning": {
        "sysWarning": "#d67d00",
        "sysOnWarning": "#ffffff",
        "sysWarningContainer": "#fdeed9",
        "sysOnWarningContainer": "#3a2304"
      },
      "info": {
        "sysInfo": "#226cee",
        "sysOnInfo": "#ffffff",
        "sysInfoContainer": "#e3f1ff",
        "sysOnInfoContainer": "#162755"
      }
    },
    "error": {
      "sysError": "#d82727",
      "sysOnError": "#ffffff",
      "sysErrorContainer": "#f7d4d4",
      "sysOnErrorContainer": "#570f0f"
    },
    "surface": {
      "surface": {
        "sysSurface": "#f3f4f6",
        "sysOnSurface": "#1b1d22",
        "sysOnSurfaceVariant": "#565f6c"
      },
      "surfaceContainer": {
        "sysSurfaceContainer": "#f3f4f6",
        "sysSurfaceContainerHighest": "#e6e8ea",
        "sysSurfaceContainerLowest": "#ffffff",
        "sysSurfaceContainerHigh": "#eceeef",
        "sysSurfaceContainerLow": "#f9fafb"
      },
      "inverse": {
        "sysInverseSurface": "#6c798b",
        "sysInverseOnSurface": "#ffffff",
        "sysInversePrimary": "#dcf0f2"
      }
    },
    "outline": {
      "sysOutline": "#f3f4f6",
      "sysOutlineVariant": "#d7dbe0",
      "sysOutlineInverse": "#ffffff66",
      "sysOutlineFixed": "#b3bbc6"
    },
    "addOn": {
      "primaryFixed": {
        "sysPrimaryFixed": "#90cdd6",
        "sysPrimaryFixedDim": "#dcf0f2",
        "sysOnPrimaryFixed": "#3f94a4",
        "sysOnPrimaryFixedVariant": "#5bb0bf"
      },
      "surfaces": {
        "sysSurfaceDim": "#eceeef",
        "sysSurfaceBright": "#ffffff"
      },
      "secondaryFixed": {
        "sysSecondaryFixed": "#fff5c7",
        "sysSecondaryFixedDim": "#fffbe5",
        "sysOnSecondaryFixed": "#b77109",
        "sysOnSecondaryFixedVariant": "#fecb31"
      }
    },
    "transparent": {
      "primary": {
        "sysPrimary08": "#00394614"
      },
      "neutral": {
        "sysWhite10": "#ffffff1a",
        "sysWhite20": "#ffffff33",
        "sysWhite30": "#ffffff4d",
        "sysWhite40": "#ffffff66",
        "sysWhite50": "#ffffff80",
        "sysBlack10": "#0000001a",
        "sysBlack20": "#00000033",
        "sysBlack30": "#0000004d",
        "sysBlack40": "#00000066",
        "sysBlack50": "#00000080",
        "sysBlack80": "#000000cc",
        "sysWhite80": "#ffffffcc"
      }
    },
    "chart": {
      "sysChartColor1": "#bde1e6",
      "sysChartColor2": "#90cdd6",
      "sysChartColor3": "#5bb0bf",
      "sysChartColor4": "#3f94a4",
      "sysChartColor5": "#367a8a",
      "sysChartColor6": "#306472",
      "sysChartColor7": "#2c535f",
      "sysChartColor8": "#003946",
      "sysChartInactive": "#eceeef"
    }
  },
  "typeScale": {
    "displayLarge": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 80,
      "sysLineHeight": 80,
      "sysTracking": -2.4
    },
    "displayMedium": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 72,
      "sysLineHeight": 80,
      "sysTracking": -1.44
    },
    "displaySmall": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 64,
      "sysLineHeight": 72,
      "sysTracking": -0.64
    },
    "headlineLarge": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 48,
      "sysLineHeight": 56,
      "sysTracking": -0.48
    },
    "headlineMedium": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 40,
      "sysLineHeight": 48,
      "sysTracking": 0
    },
    "headlineSmall": {
      "sysFontFamily": "dm serif display",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 32,
      "sysLineHeight": 40,
      "sysTracking": 0
    },
    "titleLarge": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 28,
      "sysLineHeight": 36,
      "sysTracking": 0
    },
    "titleMedium": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 24,
      "sysLineHeight": 32,
      "sysTracking": 0
    },
    "titleSmall": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 20,
      "sysLineHeight": 30,
      "sysTracking": 0
    },
    "bodyLarge": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 20,
      "sysLineHeight": 30,
      "sysTracking": 0
    },
    "bodyMedium": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 16,
      "sysLineHeight": 24,
      "sysTracking": 0
    },
    "bodySmall": {
      "sysFontFamily": "dm sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 14,
      "sysLineHeight": 20,
      "sysTracking": 0
    },
    "labelLarge": {
      "sysFontFamily": "dm mono",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 16,
      "sysLineHeight": 24,
      "sysTracking": 0
    },
    "labelMedium": {
      "sysFontFamily": "dm mono",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 14,
      "sysLineHeight": 20,
      "sysTracking": 0
    },
    "labelSmall": {
      "sysFontFamily": "dm mono",
      "sysFontWeight": "medium",
      "sysFontWeightEmphasized": "semibold",
      "sysFontSize": 12,
      "sysLineHeight": 18,
      "sysTracking": 0
    }
  },
  "dimensions": {
    "borderRadius": {
      "sysRadiusNone": 0,
      "sysRadiusXs": 4,
      "sysRadiusSm": 8,
      "sysRadiusMd": 12,
      "sysRadiusLg": 16,
      "sysRadiusLgIncreased": 20,
      "sysRadiusXl": 24,
      "sysRadiusXlIncreased": 32,
      "sysRadiusFull": 999
    },
    "spacing": {
      "margin": {
        "sysMarginSm": 16,
        "sysMarginMd": 24,
        "sysMarginLg": 32,
        "sysMarginXl": 40,
        "sysMargin2xl": 80,
        "sysMarginNone": 0
      },
      "spacer": {
        "sysSpacerSm": 16,
        "sysSpacerMd": 24,
        "sysSpacerXs": 8,
        "sysSpacerLg": 32
      },
      "padding": {
        "sysPadding2": 2,
        "sysPadding4": 4,
        "sysPadding8": 8,
        "sysPadding12": 12,
        "sysPadding16": 16,
        "sysPadding24": 24,
        "sysPadding32": 32,
        "sysPadding20": 20,
        "sysNegPadding16": -16,
        "sysNegPadding24": -24,
        "sysPadding40": 40,
        "sysPadding48": 48,
        "sysPadding64": 64,
        "sysPadding0": 0,
        "sysPadding6": 6,
        "sysPadding72": 72,
        "sysPadding80": 80
      }
    },
    "borderWidth": {
      "sysStrokeThin": 1,
      "sysStrokeMedium": 1.5,
      "sysStrokeThick": 2,
      "sysStrokeHeavier": 3,
      "sysStrokeBold": 4
    }
  },
  "iconography": {
    "sysSizeXs": 16,
    "sysSizeSm": 20,
    "sysSizeMd": 24,
    "sysSizeLg": 32,
    "sysSizeXl": 48,
    "sysSizeXxs": 12
  },
  "stateLayer": {
    "sysHover": 10,
    "sysPressed": 20,
    "sysFocused": 16,
    "sysDisabledContainer": 20,
    "sysDisabledContent": 20,
    "sysScrim": 10
  },
  "elevation": {
    "sysLevel0": {
      "shadow": {
        "color": "#00000000",
        "type": "dropShadow",
        "x": 0,
        "y": 0,
        "blur": 0,
        "spread": 0
      },
      "sysSurfaceTintOpacity": 0
    },
    "sysLevel1": {
      "shadow": {
        "1": {
          "color": "#0000000f",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 4,
          "spread": 0
        },
        "2": {
          "color": "#0000000a",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 8,
          "spread": 0
        }
      },
      "sysSurfaceTintOpacity": 0.05
    },
    "sysLevel2": {
      "shadow": {
        "1": {
          "color": "#00000014",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 4,
          "spread": 0
        },
        "2": {
          "color": "#0000001a",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 16,
          "spread": 0
        }
      },
      "sysSurfaceTintOpacity": 0.08
    },
    "sysLevel3": {
      "shadow": {
        "1": {
          "color": "#0000001f",
          "type": "dropShadow",
          "x": 0,
          "y": 2,
          "blur": 6,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 16,
          "spread": 0
        }
      },
      "sysSurfaceTintOpacity": 0.11
    },
    "sysLevel4": {
      "shadow": {
        "1": {
          "color": "#0000001a",
          "type": "dropShadow",
          "x": 0,
          "y": 4,
          "blur": 8,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 6,
          "blur": 20,
          "spread": 0
        }
      },
      "sysSurfaceTintOpacity": 0.12
    },
    "sysLevel5": {
      "shadow": {
        "1": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 5,
          "blur": 8,
          "spread": 0
        },
        "2": {
          "color": "#00000029",
          "type": "dropShadow",
          "x": 0,
          "y": 8,
          "blur": 20,
          "spread": 0
        }
      },
      "sysSurfaceTintOpacity": 0.14
    }
  }
} as const;

export type Sys = typeof sys;

// Convenience alias — wraps `sys` as `tokens.sys` for adopters
// that prefer the namespaced shape in a ThemeProvider.
export const tokens = { sys };
