// Auto-generated by tokens/build.ts. Do not edit by hand.
// Run `npm run build:tokens` to regenerate.

export const sys = {
  "colorRoles": {
    "accent": {
      "primary": {
        "sysPrimary": "#075cba",
        "sysOnPrimary": "#ffffff",
        "sysOnPrimaryContainer": "#ffffff",
        "sysPrimaryContainer": "#070f36",
        "sysOnPrimaryContainerVariant": "#b9dcff"
      },
      "secondary": {
        "sysSecondary": "#ffffff",
        "sysOnSecondary": "#1b1d22",
        "sysSecondaryContainer": "#ffffff",
        "sysOnSecondaryContainer": "#1b1d22"
      },
      "tertiary": {
        "sysTertiary": "#f3f4f6",
        "sysOnTertiary": "#1b1d22",
        "sysTertiaryContainer": "#ffffff",
        "sysOnTertiaryContainer": "#1b1d22"
      }
    },
    "custom": {
      "success": {
        "sysSuccess": "#278647",
        "sysOnSuccess": "#ffffff",
        "sysSuccessContainer": "#c4e9d0",
        "sysOnSuccessContainer": "#030c09"
      },
      "warning": {
        "sysWarning": "#d67d00",
        "sysOnWarning": "#ffffff",
        "sysWarningContainer": "#fdeed9",
        "sysOnWarningContainer": "#3a2304"
      },
      "info": {
        "sysInfo": "#226cee",
        "sysOnInfo": "#ffffff",
        "sysInfoContainer": "#daecff",
        "sysOnInfoContainer": "#162755"
      }
    },
    "error": {
      "sysError": "#d82727",
      "sysOnError": "#ffffff",
      "sysErrorContainer": "#f7d4d4",
      "sysOnErrorContainer": "#570f0f"
    },
    "surface": {
      "surface": {
        "sysSurface": "#f3f4f6",
        "sysOnSurface": "#1b1d22",
        "sysOnSurfaceVariant": "#565f6c"
      },
      "surfaceContainer": {
        "sysSurfaceContainer": "#f3f4f6",
        "sysSurfaceContainerHighest": "#e6e8ea",
        "sysSurfaceContainerLowest": "#ffffff",
        "sysSurfaceContainerHigh": "#eceeef",
        "sysSurfaceContainerLow": "#f9fafb"
      },
      "inverse": {
        "sysInverseSurface": "#474f5d",
        "sysInverseOnSurface": "#ffffff",
        "sysInversePrimary": "#b9dcff"
      }
    },
    "outline": {
      "sysOutline": "#eceeef",
      "sysOutlineVariant": "#d7dbe0",
      "sysOutlineInverse": "#ffffff66",
      "sysOutlineFixed": "#b3bbc6"
    },
    "addOn": {
      "primaryFixed": {
        "sysPrimaryFixed": "#82b1ff",
        "sysPrimaryFixedDim": "#e3f2fd",
        "sysOnPrimaryFixed": "#075cba",
        "sysOnPrimaryFixedVariant": "#4285f4"
      },
      "surfaces": {
        "sysSurfaceDim": "#eceeef",
        "sysSurfaceBright": "#ffffff"
      },
      "secondaryFixed": {
        "sysSecondaryFixed": "#cccccc",
        "sysSecondaryFixedDim": "#e6e6e6",
        "sysOnSecondaryFixed": "#1a1a1a",
        "sysOnSecondaryFixedVariant": "#666666"
      }
    },
    "transparent": {
      "primary": {
        "sysPrimary08": "#075cba14"
      },
      "neutral": {
        "sysWhite10": "#ffffff1a",
        "sysWhite20": "#ffffff33",
        "sysWhite30": "#ffffff4d",
        "sysWhite40": "#ffffff66",
        "sysWhite50": "#ffffff80",
        "sysBlack10": "#0000001a",
        "sysBlack20": "#00000033",
        "sysBlack30": "#0000004d",
        "sysBlack40": "#00000066",
        "sysBlack50": "#00000080",
        "sysBlack80": "#000000cc",
        "sysWhite80": "#ffffffcc"
      }
    },
    "chart": {
      "sysChartColor1": "#b9dcff",
      "sysChartColor2": "#82b1ff",
      "sysChartColor3": "#4285f4",
      "sysChartColor4": "#075cba",
      "sysChartColor5": "#062e6f",
      "sysChartColor6": "#061545",
      "sysChartColor7": "#070f36",
      "sysChartColor8": "#050a24",
      "sysChartInactive": "#eceeef"
    }
  },
  "typeScale": {
    "displayLarge": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 80,
      "sysLineHeight": 80,
      "sysTracking": -2.4
    },
    "displayMedium": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 72,
      "sysLineHeight": 80,
      "sysTracking": -1.44
    },
    "displaySmall": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 64,
      "sysLineHeight": 72,
      "sysTracking": -0.64
    },
    "headlineLarge": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 48,
      "sysLineHeight": 56,
      "sysTracking": -0.48
    },
    "headlineMedium": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 40,
      "sysLineHeight": 48,
      "sysTracking": 0
    },
    "headlineSmall": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 32,
      "sysLineHeight": 40,
      "sysTracking": 0
    },
    "titleLarge": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 28,
      "sysLineHeight": 36,
      "sysTracking": 0
    },
    "titleMedium": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 24,
      "sysLineHeight": 32,
      "sysTracking": 0
    },
    "titleSmall": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 20,
      "sysLineHeight": 30,
      "sysTracking": 0
    },
    "bodyLarge": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 20,
      "sysLineHeight": 30,
      "sysTracking": 0
    },
    "bodyMedium": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 16,
      "sysLineHeight": 24,
      "sysTracking": 0
    },
    "bodySmall": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 14,
      "sysLineHeight": 20,
      "sysTracking": 0
    },
    "labelLarge": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 16,
      "sysLineHeight": 24,
      "sysTracking": 0
    },
    "labelMedium": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "regular",
      "sysFontWeightEmphasized": "medium",
      "sysFontSize": 14,
      "sysLineHeight": 20,
      "sysTracking": 0
    },
    "labelSmall": {
      "sysFontFamily": "google sans",
      "sysFontWeight": "medium",
      "sysFontWeightEmphasized": "semibold",
      "sysFontSize": 12,
      "sysLineHeight": 18,
      "sysTracking": 0
    }
  },
  "dimensions": {
    "borderRadius": {
      "sysRadiusNone": 0,
      "sysRadiusXs": 4,
      "sysRadiusSm": 8,
      "sysRadiusMd": 12,
      "sysRadiusLg": 16,
      "sysRadiusLgIncreased": 20,
      "sysRadiusXl": 24,
      "sysRadiusXlIncreased": 32,
      "sysRadiusFull": 999
    },
    "spacing": {
      "margin": {
        "sysMarginSm": 16,
        "sysMarginMd": 24,
        "sysMarginLg": 32,
        "sysMarginXl": 40,
        "sysMargin2xl": 80,
        "sysMarginNone": 0
      },
      "spacer": {
        "sysSpacerSm": 16,
        "sysSpacerMd": 24,
        "sysSpacerXs": 8,
        "sysSpacerLg": 32
      },
      "padding": {
        "sysPadding2": 2,
        "sysPadding4": 4,
        "sysPadding8": 8,
        "sysPadding12": 12,
        "sysPadding16": 16,
        "sysPadding24": 24,
        "sysPadding32": 32,
        "sysPadding20": 20,
        "sysNegPadding16": -16,
        "sysNegPadding24": -24,
        "sysPadding40": 40,
        "sysPadding48": 48,
        "sysPadding64": 64,
        "sysPadding0": 0,
        "sysPadding6": 6,
        "sysPadding72": 72,
        "sysPadding80": 80
      }
    },
    "borderWidth": {
      "sysStrokeThin": 1,
      "sysStrokeMedium": 1.5,
      "sysStrokeThick": 2,
      "sysStrokeHeavier": 3,
      "sysStrokeBold": 4
    }
  },
  "iconography": {
    "sysSizeXs": 16,
    "sysSizeSm": 20,
    "sysSizeMd": 24,
    "sysSizeLg": 32,
    "sysSizeXl": 48,
    "sysSizeXxs": 12
  },
  "stateLayer": {
    "sysHover": 8,
    "sysPressed": 10,
    "sysFocused": 12,
    "sysDisabledContainer": 48,
    "sysDisabledContent": 64,
    "sysScrim": 10
  }
} as const;

export type Sys = typeof sys;

// Convenience alias — wraps `sys` as `tokens.sys` for adopters
// that prefer the namespaced shape in a ThemeProvider.
export const tokens = { sys };
